# Dockerfile.test
FROM python:3.9-slim

WORKDIR /code

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt
RUN pip install pytest==8.3.2

COPY ./app ./app
COPY ./tests ./tests

CMD ["pytest"]