version: '3.8' # Specifies the version of Docker Compose

services:
  # Defines the services that make up your application

  app:
    # The application service
    build: . # Builds the Docker image from the current directory (context)
    ports:
      - "8000:8000" # Maps port 8000 on the host to port 8000 on the container
    environment:
      - REDIS_HOST=redis # Sets the environment variable REDIS_HOST to 'redis'
    volumes:
      - ./app:/code/app # Maps the local ./app directory to /code/app in the container
    depends_on:
      - redis # Specifies that the 'app' service depends on the 'redis' service

  redis:
    # The Redis service
    image: redis:alpine # Uses the Redis image with the Alpine tag
    ports:
      - "6379:6379" # Maps port 6379 on the host to port 6379 on the container
