name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==8.3.2

      - name: Run tests
        run: |
          pytest --maxfail=10 --disable-warnings

      - name: Lint code
        run: |
          pip install flake8
          flake8 app tests

      - name: Build Docker image
        run: docker build -t my-fastapi-app .

      - name: Run FastAPI application
        run: docker run -d -p 8000:8000 my-fastapi-app

      - name: Verify application is running
        run: |
          sleep 10
          curl --fail http://localhost:8000 || exit 1
